version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
